"""
add_missing_regs_ai.py — Add 20 major missing regulations using Claude AI.

Generates fully-structured regulation entries (metadata + key_requirements with
all 7 fields) and merges them into data/regulations.json.

Safe to re-run: skips regulations whose id already exists in the file.

Usage:
    set ANTHROPIC_API_KEY=sk-ant-...
    python scripts/add_missing_regs_ai.py

After running:
    python scripts/enrich_requirements.py   # fill any missing how_to_meet fields
    python scripts/check_regulation_updates.py  # rebuild hashes

Cost estimate: ~20 regulations × ~2000 output tokens = ~$0.30 (claude-haiku)
"""

import json
import sys
import os
import time
import re
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

try:
    import anthropic
except ImportError:
    raise SystemExit("Run:  pip install anthropic")

# ---------------------------------------------------------------------------
REGS_FILE  = Path(__file__).parent.parent / "data" / "regulations.json"
MODEL      = "claude-haiku-4-5-20251001"
MAX_TOKENS = 6000
RATE_DELAY = 0.5
# ---------------------------------------------------------------------------

EU_COUNTRIES = [
    "AT","BE","BG","HR","CY","CZ","DK","EE","FI","FR","DE","GR",
    "HU","IE","IT","LV","LT","LU","MT","NL","PL","PT","RO","SK",
    "SI","ES","SE","IS","LI","NO"
]

# ---------------------------------------------------------------------------
# 20 regulations to add — basic metadata only; requirements generated by Claude
# ---------------------------------------------------------------------------
MISSING_REGS = [

    # ── EU ──────────────────────────────────────────────────────────────────
    {
        "id": "EU_DSA",
        "name": "Digital Services Act",
        "short_name": "EU DSA",
        "domain": ["data_privacy", "cybersecurity"],
        "jurisdiction": "European Union",
        "enforcement_region": "eu",
        "geography": {"type": "regional", "regions": ["EU"], "countries": EU_COUNTRIES},
        "status": "active",
        "effective_date": "2024-02-17",
        "authority": "European Commission / Digital Services Coordinators",
        "url": "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32022R2065",
        "summary": "EU regulation imposing transparency, accountability, and content moderation obligations on digital intermediaries and online platforms. Very large online platforms (VLOPs) and search engines (VLOSEs) face the strictest duties including algorithmic audits, risk assessments, and access for researchers.",
        "penalty_severity": 4,
        "enforcement_intensity": 2,
        "milestones": [
            {"date": "2023-08-25", "label": "Obligations for VLOPs/VLOSEs", "status": "past"},
            {"date": "2024-02-17", "label": "Full application to all intermediaries", "status": "past"}
        ]
    },
    {
        "id": "EU_DMA",
        "name": "Digital Markets Act",
        "short_name": "EU DMA",
        "domain": ["finance", "cybersecurity"],
        "jurisdiction": "European Union",
        "enforcement_region": "eu",
        "geography": {"type": "regional", "regions": ["EU"], "countries": EU_COUNTRIES},
        "status": "active",
        "effective_date": "2023-05-02",
        "authority": "European Commission (DG COMP)",
        "url": "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32022R1925",
        "summary": "Regulation designating large tech platforms as 'gatekeepers' and imposing ex-ante obligations to ensure contestable and fair digital markets. Covers app stores, search engines, messaging, browsers, and operating systems with obligations around interoperability, data portability, and self-preferencing bans.",
        "penalty_severity": 5,
        "enforcement_intensity": 2,
        "milestones": [
            {"date": "2023-03-07", "label": "First gatekeeper designations", "status": "past"},
            {"date": "2024-03-07", "label": "Core platform obligations deadline", "status": "past"}
        ]
    },
    {
        "id": "EU_DATA_ACT",
        "name": "EU Data Act",
        "short_name": "EU Data Act",
        "domain": ["data_privacy", "finance"],
        "jurisdiction": "European Union",
        "enforcement_region": "eu",
        "geography": {"type": "regional", "regions": ["EU"], "countries": EU_COUNTRIES},
        "status": "active",
        "effective_date": "2025-09-12",
        "authority": "European Commission / National Data Authorities",
        "url": "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32023R2854",
        "summary": "Horizontal EU regulation establishing rules on access to and use of data generated by connected products (IoT) and related services. It gives users the right to access and share data generated by their devices, imposes data sharing obligations on manufacturers, and regulates cloud switching to prevent vendor lock-in.",
        "penalty_severity": 4,
        "enforcement_intensity": 1,
        "milestones": [
            {"date": "2024-01-11", "label": "Regulation enters into force", "status": "past"},
            {"date": "2025-09-12", "label": "Full application date", "status": "upcoming"}
        ]
    },
    {
        "id": "EU_DGA",
        "name": "EU Data Governance Act",
        "short_name": "EU DGA",
        "domain": ["data_privacy"],
        "jurisdiction": "European Union",
        "enforcement_region": "eu",
        "geography": {"type": "regional", "regions": ["EU"], "countries": EU_COUNTRIES},
        "status": "active",
        "effective_date": "2023-09-24",
        "authority": "European Commission / National Competent Authorities",
        "url": "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32022R0868",
        "summary": "EU regulation creating a framework for voluntary data sharing in the public interest, governing data intermediaries, data altruism organisations, and re-use of public sector data. Establishes registration requirements for data intermediary service providers and data altruism organisations.",
        "penalty_severity": 3,
        "enforcement_intensity": 1,
        "milestones": [
            {"date": "2023-09-24", "label": "Full application date", "status": "past"}
        ]
    },
    {
        "id": "EU_MICA",
        "name": "Markets in Crypto-Assets Regulation",
        "short_name": "EU MiCA",
        "domain": ["finance", "cybersecurity"],
        "jurisdiction": "European Union",
        "enforcement_region": "eu",
        "geography": {"type": "regional", "regions": ["EU"], "countries": EU_COUNTRIES},
        "status": "active",
        "effective_date": "2024-12-30",
        "authority": "European Securities and Markets Authority (ESMA) / European Banking Authority (EBA)",
        "url": "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32023R1114",
        "summary": "Comprehensive EU regulatory framework for crypto-assets not covered by existing financial legislation. MiCA introduces licensing requirements for crypto-asset service providers (CASPs), whitepaper obligations for issuers of crypto-assets and stablecoins, and consumer protection and market integrity rules.",
        "penalty_severity": 4,
        "enforcement_intensity": 2,
        "milestones": [
            {"date": "2024-06-30", "label": "Stablecoins provisions apply", "status": "past"},
            {"date": "2024-12-30", "label": "Full CASP licensing requirements apply", "status": "past"}
        ]
    },
    {
        "id": "EU_SFDR",
        "name": "Sustainable Finance Disclosure Regulation",
        "short_name": "EU SFDR",
        "domain": ["finance", "esg"],
        "jurisdiction": "European Union",
        "enforcement_region": "eu",
        "geography": {"type": "regional", "regions": ["EU"], "countries": EU_COUNTRIES},
        "status": "active",
        "effective_date": "2021-03-10",
        "authority": "European Securities and Markets Authority (ESMA)",
        "url": "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32019R2088",
        "summary": "EU regulation requiring financial market participants and financial advisers to make sustainability-related disclosures on their websites and in pre-contractual and periodic documents. Classifies funds into Article 6 (no sustainability focus), Article 8 (ESG integration), and Article 9 (sustainable investment) categories.",
        "penalty_severity": 3,
        "enforcement_intensity": 2,
        "milestones": [
            {"date": "2021-03-10", "label": "Level 1 disclosure requirements apply", "status": "past"},
            {"date": "2023-01-01", "label": "Level 2 RTS (detailed disclosures) apply", "status": "past"}
        ]
    },

    # ── UK ──────────────────────────────────────────────────────────────────
    {
        "id": "UK_DPA_2018",
        "name": "UK General Data Protection Regulation / Data Protection Act 2018",
        "short_name": "UK GDPR / DPA 2018",
        "domain": ["data_privacy"],
        "jurisdiction": "United Kingdom",
        "enforcement_region": "uk",
        "geography": {"type": "national", "regions": ["UK"], "countries": ["GB"]},
        "status": "active",
        "effective_date": "2021-01-01",
        "authority": "Information Commissioner's Office (ICO)",
        "url": "https://www.legislation.gov.uk/ukpga/2018/12/contents",
        "summary": "The UK's post-Brexit data protection framework, comprising the retained UK GDPR and the Data Protection Act 2018. Functionally equivalent to EU GDPR but with UK-specific provisions, governed by the ICO. Applies to all organisations processing personal data of UK residents regardless of where the organisation is based.",
        "penalty_severity": 5,
        "enforcement_intensity": 3,
        "milestones": [
            {"date": "2021-01-01", "label": "UK GDPR takes effect post-Brexit", "status": "past"}
        ]
    },
    {
        "id": "UK_ONLINE_SAFETY_ACT",
        "name": "Online Safety Act 2023",
        "short_name": "UK Online Safety Act",
        "domain": ["cybersecurity", "data_privacy"],
        "jurisdiction": "United Kingdom",
        "enforcement_region": "uk",
        "geography": {"type": "national", "regions": ["UK"], "countries": ["GB"]},
        "status": "active",
        "effective_date": "2024-03-01",
        "authority": "Ofcom",
        "url": "https://www.legislation.gov.uk/ukpga/2023/50/contents",
        "summary": "Landmark UK legislation placing legal duties on online services to protect users from illegal and harmful content. User-to-user services and search engines must conduct risk assessments, implement safety measures, and are subject to mandatory child safety duties. Ofcom can impose fines up to 10% of global annual revenue for non-compliance.",
        "penalty_severity": 4,
        "enforcement_intensity": 2,
        "milestones": [
            {"date": "2024-03-01", "label": "Illegal content duties begin", "status": "past"},
            {"date": "2025-07-01", "label": "Child safety and transparency duties", "status": "upcoming"}
        ]
    },

    # ── US Federal ───────────────────────────────────────────────────────────
    {
        "id": "CIRCIA",
        "name": "Cyber Incident Reporting for Critical Infrastructure Act 2022",
        "short_name": "CIRCIA",
        "domain": ["cybersecurity", "critical_infrastructure"],
        "jurisdiction": "United States - Federal",
        "enforcement_region": "us_federal",
        "geography": {"type": "national", "regions": ["North America"], "countries": ["US"]},
        "status": "active",
        "effective_date": "2024-04-04",
        "authority": "Cybersecurity and Infrastructure Security Agency (CISA)",
        "url": "https://www.cisa.gov/circia",
        "summary": "US federal law requiring critical infrastructure entities to report significant cyber incidents to CISA within 72 hours and ransomware payments within 24 hours. CISA is developing implementing regulations (NPRM expected 2025) that will define covered entities, incidents, and reporting timelines. Covers 16 critical infrastructure sectors.",
        "penalty_severity": 4,
        "enforcement_intensity": 2,
        "milestones": [
            {"date": "2024-04-04", "label": "Law enacted; NPRM period begins", "status": "past"},
            {"date": "2025-10-01", "label": "Final CIRCIA rule expected", "status": "upcoming"},
            {"date": "2026-04-01", "label": "Full compliance requirements take effect", "status": "upcoming"}
        ]
    },
    {
        "id": "FERPA",
        "name": "Family Educational Rights and Privacy Act",
        "short_name": "FERPA",
        "domain": ["data_privacy"],
        "jurisdiction": "United States - Federal",
        "enforcement_region": "us_federal",
        "geography": {"type": "national", "regions": ["North America"], "countries": ["US"]},
        "status": "active",
        "effective_date": "1974-08-21",
        "authority": "US Department of Education",
        "url": "https://studentprivacy.ed.gov/ferpa",
        "summary": "US federal law protecting the privacy of student education records. Applies to all schools receiving US Department of Education funding. Parents and eligible students (18+) have rights to inspect records, request amendments, and control disclosures. Schools must have written consent before disclosing personally identifiable information from education records.",
        "penalty_severity": 3,
        "enforcement_intensity": 2,
        "milestones": []
    },

    # ── US States ────────────────────────────────────────────────────────────
    {
        "id": "TX_TDPSA",
        "name": "Texas Data Privacy and Security Act",
        "short_name": "Texas TDPSA",
        "domain": ["data_privacy"],
        "jurisdiction": "State of Texas",
        "enforcement_region": "us_state",
        "geography": {"type": "state", "regions": ["North America"], "countries": ["US"]},
        "status": "active",
        "effective_date": "2024-07-01",
        "authority": "Texas Attorney General",
        "url": "https://capitol.texas.gov/tlodocs/88R/billtext/pdf/SB02105F.pdf",
        "summary": "Texas comprehensive privacy law granting consumers rights over their personal data and imposing duties on controllers and processors. Notably does not have a revenue threshold — it applies to businesses that conduct business in Texas or target Texas residents and process personal data of 100,000+ consumers annually or 25,000+ consumers if deriving 25%+ of revenue from selling personal data.",
        "penalty_severity": 3,
        "enforcement_intensity": 2,
        "milestones": []
    },
    {
        "id": "CT_CTDPA",
        "name": "Connecticut Data Privacy Act",
        "short_name": "Connecticut CTDPA",
        "domain": ["data_privacy"],
        "jurisdiction": "State of Connecticut",
        "enforcement_region": "us_state",
        "geography": {"type": "state", "regions": ["North America"], "countries": ["US"]},
        "status": "active",
        "effective_date": "2023-07-01",
        "authority": "Connecticut Attorney General",
        "url": "https://www.cga.ct.gov/2022/ACT/PA/PDF/2022PA-00015-R00SB-00006-PA.PDF",
        "summary": "Connecticut's comprehensive data privacy law granting residents the right to access, correct, delete, and port their personal data, and to opt out of targeted advertising, sale, or profiling. Applies to controllers processing data of 100,000+ Connecticut residents, or 25,000+ if deriving over 25% revenue from personal data sales. Includes a 60-day cure period.",
        "penalty_severity": 3,
        "enforcement_intensity": 2,
        "milestones": []
    },
    {
        "id": "NJ_NJDPA",
        "name": "New Jersey Data Privacy Act",
        "short_name": "New Jersey NJDPA",
        "domain": ["data_privacy"],
        "jurisdiction": "State of New Jersey",
        "enforcement_region": "us_state",
        "geography": {"type": "state", "regions": ["North America"], "countries": ["US"]},
        "status": "active",
        "effective_date": "2025-01-15",
        "authority": "New Jersey Attorney General",
        "url": "https://www.njleg.state.nj.us/Bills/2022/PL23/266_.PDF",
        "summary": "New Jersey's comprehensive consumer data privacy law granting residents rights to access, correct, delete, and obtain a copy of their personal data, and to opt out of targeted advertising, data sales, and certain profiling. Applies to controllers processing data of 100,000+ NJ consumers (or 25,000+ with revenue from data sales). Notable for applying to nonprofits.",
        "penalty_severity": 3,
        "enforcement_intensity": 1,
        "milestones": []
    },

    # ── Germany ──────────────────────────────────────────────────────────────
    {
        "id": "DE_BSIG2",
        "name": "IT-Sicherheitsgesetz 2.0 / BSIG (Germany)",
        "short_name": "Germany IT-SiG 2.0",
        "domain": ["cybersecurity", "critical_infrastructure"],
        "jurisdiction": "Federal Republic of Germany",
        "enforcement_region": "europe_other",
        "geography": {"type": "national", "regions": ["Europe"], "countries": ["DE"]},
        "status": "active",
        "effective_date": "2021-05-28",
        "authority": "Bundesamt für Sicherheit in der Informationstechnik (BSI)",
        "url": "https://www.bsi.bund.de/EN/Themen/Unternehmen-und-Organisationen/Standards-und-Zertifizierung/IT-Sicherheitsgesetz/it-sicherheitsgesetz_node.html",
        "summary": "Germany's second IT Security Act significantly expanding the scope of critical infrastructure cybersecurity obligations. Expands KRITIS sectors, introduces a new category of 'companies in the special public interest' (UBI), mandates attack detection systems (Angriffserkennung), and grants BSI broader monitoring and intervention powers.",
        "penalty_severity": 4,
        "enforcement_intensity": 2,
        "milestones": [
            {"date": "2021-05-28", "label": "Law enacted", "status": "past"},
            {"date": "2023-05-01", "label": "Attack detection system requirements for KRITIS", "status": "past"}
        ]
    },

    # ── Australia ─────────────────────────────────────────────────────────────
    {
        "id": "AU_CPS234",
        "name": "APRA Prudential Standard CPS 234 — Information Security",
        "short_name": "Australia CPS 234",
        "domain": ["cybersecurity", "finance"],
        "jurisdiction": "Commonwealth of Australia",
        "enforcement_region": "australia",
        "geography": {"type": "national", "regions": ["APAC"], "countries": ["AU"]},
        "status": "active",
        "effective_date": "2019-07-01",
        "authority": "Australian Prudential Regulation Authority (APRA)",
        "url": "https://www.apra.gov.au/sites/default/files/2019-08/Prudential%20Standard%20CPS%20234%20Information%20Security.pdf",
        "summary": "APRA prudential standard mandating that APRA-regulated entities (banks, insurers, superannuation funds) maintain information security capability commensurate with their role in the financial system. Requires defined information security roles, adequate controls, systematic testing, and notification to APRA of material incidents within 72 hours.",
        "penalty_severity": 4,
        "enforcement_intensity": 2,
        "milestones": []
    },

    # ── Singapore ─────────────────────────────────────────────────────────────
    {
        "id": "SG_MAS_TRM",
        "name": "MAS Technology Risk Management Guidelines 2021",
        "short_name": "Singapore MAS TRM",
        "domain": ["cybersecurity", "finance"],
        "jurisdiction": "Republic of Singapore",
        "enforcement_region": "singapore",
        "geography": {"type": "national", "regions": ["APAC"], "countries": ["SG"]},
        "status": "active",
        "effective_date": "2021-01-18",
        "authority": "Monetary Authority of Singapore (MAS)",
        "url": "https://www.mas.gov.sg/regulation/guidelines/technology-risk-management-guidelines",
        "summary": "MAS guidelines setting out risk management principles and best practices for financial institutions to protect against technology and cyber risks. Covers board and senior management accountability, technology risk governance, IT asset and project management, software development security, cyber resilience, and third-party risk management.",
        "penalty_severity": 3,
        "enforcement_intensity": 2,
        "milestones": []
    },

    # ── India ─────────────────────────────────────────────────────────────────
    {
        "id": "IN_IT_ACT",
        "name": "Information Technology Act 2000 (as amended 2008)",
        "short_name": "India IT Act",
        "domain": ["cybersecurity", "data_privacy"],
        "jurisdiction": "Republic of India",
        "enforcement_region": "india",
        "geography": {"type": "national", "regions": ["South Asia"], "countries": ["IN"]},
        "status": "active",
        "effective_date": "2000-10-17",
        "authority": "Ministry of Electronics and Information Technology (MeitY) / CERT-In",
        "url": "https://www.meity.gov.in/content/information-technology-act",
        "summary": "India's primary legislation governing cybercrime, electronic commerce, and data protection. The 2008 amendment introduced Section 43A (reasonable security practices for sensitive personal data) and Section 66A-72A (offences). CERT-In directions under Section 70B require 6-hour incident reporting to CERT-In and 180-day log retention for a wide range of entities.",
        "penalty_severity": 3,
        "enforcement_intensity": 2,
        "milestones": [
            {"date": "2022-06-27", "label": "CERT-In directions: 6-hour reporting mandatory", "status": "past"}
        ]
    },

    # ── China ─────────────────────────────────────────────────────────────────
    {
        "id": "CN_MLPS2",
        "name": "Multi-Level Protection Scheme 2.0 (等级保护 2.0)",
        "short_name": "China MLPS 2.0",
        "domain": ["cybersecurity", "data_privacy"],
        "jurisdiction": "People's Republic of China",
        "enforcement_region": "china",
        "geography": {"type": "national", "regions": ["East Asia"], "countries": ["CN"]},
        "status": "active",
        "effective_date": "2019-12-01",
        "authority": "Ministry of Public Security (MPS) / Cyberspace Administration of China (CAC)",
        "url": "https://www.tc260.org.cn/",
        "summary": "China's mandatory network security classification system requiring all operators of networks to classify their systems from Level 1 (lowest risk) to Level 5 (highest, national critical infrastructure) and implement corresponding security controls. Level 2+ systems require filing with public security authorities and regular security assessments. Superseded the original MLPS 1.0 standard.",
        "penalty_severity": 5,
        "enforcement_intensity": 3,
        "milestones": []
    },

    # ── Japan ─────────────────────────────────────────────────────────────────
    {
        "id": "JP_CYBER_BASIC_ACT",
        "name": "Act on Basic Strategy for Cybersecurity (Cybersecurity Basic Act)",
        "short_name": "Japan Cybersecurity Act",
        "domain": ["cybersecurity", "critical_infrastructure"],
        "jurisdiction": "Japan",
        "enforcement_region": "japan",
        "geography": {"type": "national", "regions": ["East Asia"], "countries": ["JP"]},
        "status": "active",
        "effective_date": "2015-01-09",
        "authority": "National center of Incident readiness and Strategy for Cybersecurity (NISC)",
        "url": "https://www.nisc.go.jp/eng/",
        "summary": "Japan's foundational cybersecurity legislation establishing the Cybersecurity Strategic Headquarters and NISC, and defining national cybersecurity strategy. Requires critical infrastructure providers in 14 designated sectors to participate in information sharing, comply with government cybersecurity policy, and cooperate with NISC investigations.",
        "penalty_severity": 3,
        "enforcement_intensity": 1,
        "milestones": []
    },

    # ── South Korea ───────────────────────────────────────────────────────────
    {
        "id": "KR_ISMS_P",
        "name": "Information Security Management System — Personal Information (ISMS-P)",
        "short_name": "South Korea ISMS-P",
        "domain": ["cybersecurity", "data_privacy"],
        "jurisdiction": "Republic of Korea",
        "enforcement_region": "south_korea",
        "geography": {"type": "national", "regions": ["East Asia"], "countries": ["KR"]},
        "status": "active",
        "effective_date": "2019-11-07",
        "authority": "Korea Internet & Security Agency (KISA) / Korea Communications Commission (KCC)",
        "url": "https://isms.kisa.or.kr/main/isms/intro/",
        "summary": "South Korea's mandatory certification scheme combining the ISMS (Information Security Management System) and PIMS (Personal Information Management System) into a unified framework. Certain ISPs, hospitals, universities, and businesses meeting revenue/user thresholds must obtain ISMS-P certification — a 102-control audit covering technical, managerial, and operational security and personal data protection.",
        "penalty_severity": 4,
        "enforcement_intensity": 2,
        "milestones": []
    },
]

# ---------------------------------------------------------------------------
SCHEMA_PROMPT = """You are an expert compliance data engineer. Generate key_requirements for the regulation below, following EXACTLY the JSON schema of this example from GDPR:

{
  "id": "GDPR-R001",
  "title": "Lawful Basis for Processing",
  "text": "Establish and document a lawful basis for every personal data processing activity",
  "consequence": "Unlawful processing; fines up to €20M or 4% global annual turnover",
  "evidence_guide": "Records of Processing Activities (RoPA); legitimate interest assessments; consent records",
  "control_theme": "data_governance",
  "how_to_meet": "1. Conduct a comprehensive data inventory mapping all processing activities, data categories, and purposes. 2. Document the legal basis for each processing activity in a Records of Processing Activities register. 3. Perform and retain Legitimate Interest Assessments for any processing relying on legitimate interest.",
  "internal_actions": "Legal team: provide signed Records of Processing Activities template and completed ROPA for all departments. Compliance team: maintain master register of lawful basis determinations and conduct annual review.",
  "vendor_actions": "Vendors: provide written confirmation of the lawful basis under which they process data on your behalf and sign Data Processing Addendum explicitly stating their processing activities and legal basis.",
  "compliance_evidence": "Signed Records of Processing Activities register, dated Legitimate Interest Assessments, Data Processing Agreements with all vendors, internal policy document citing legal basis for each processing activity."
}

Valid control_theme values: access_control, board_governance, data_governance, financial_controls, incident_response, policy_procedures, risk_assessment, technical_controls, training_awareness, vendor_management

REGULATION TO GENERATE REQUIREMENTS FOR:
Name: {name}
Jurisdiction: {jurisdiction}
Domain: {domain}
Summary: {summary}

Generate 5-7 key requirements that cover the most important compliance obligations of this regulation.
Each requirement must have all 9 fields: id, title, text, consequence, evidence_guide, control_theme, how_to_meet, internal_actions, vendor_actions, compliance_evidence.

Requirement IDs must use the pattern: {id_prefix}-R001, {id_prefix}-R002, etc.
Return ONLY a valid JSON array. No markdown, no code fences, no explanation."""


def strip_fences(raw: str) -> str:
    raw = raw.strip()
    if raw.startswith("```"):
        parts = raw.split("```")
        raw = parts[1] if len(parts) > 1 else raw
        if raw.startswith("json"):
            raw = raw[4:]
    return raw.strip()


def generate_requirements(client: anthropic.Anthropic, reg: dict) -> list:
    id_prefix = reg["id"].replace("_", "-").replace("-", "_")
    prompt = SCHEMA_PROMPT.format(
        name=reg["name"],
        jurisdiction=reg["jurisdiction"],
        domain=", ".join(reg["domain"]),
        summary=reg["summary"],
        id_prefix=reg["id"].replace("_", "-")
    )
    msg = client.messages.create(
        model=MODEL,
        max_tokens=MAX_TOKENS,
        messages=[{"role": "user", "content": prompt}]
    )
    raw = strip_fences(msg.content[0].text)
    return json.loads(raw)


def main():
    api_key = os.environ.get("ANTHROPIC_API_KEY", "")
    if not api_key:
        raise SystemExit(
            "Set ANTHROPIC_API_KEY environment variable before running.\n"
            "  Windows: set ANTHROPIC_API_KEY=sk-ant-...\n"
            "  macOS/Linux: export ANTHROPIC_API_KEY=sk-ant-..."
        )

    client = anthropic.Anthropic(api_key=api_key)

    with open(REGS_FILE, encoding="utf-8") as f:
        doc = json.load(f)

    existing_ids = {r["id"] for r in doc["regulations"]}
    to_add = [r for r in MISSING_REGS if r["id"] not in existing_ids]

    if not to_add:
        print("All regulations already present in regulations.json — nothing to do.")
        return

    print(f"Found {len(to_add)} regulations to add (skipping {len(MISSING_REGS) - len(to_add)} already present)\n")

    added = 0
    errors = []

    for i, reg in enumerate(to_add, 1):
        print(f"[{i}/{len(to_add)}] Generating requirements for {reg['short_name']} ({reg['id']})...", flush=True)
        try:
            reqs = generate_requirements(client, reg)
            reg_entry = {k: v for k, v in reg.items()}
            reg_entry["key_requirements"] = reqs
            doc["regulations"].append(reg_entry)
            added += 1
            print(f"         ✓ Added {len(reqs)} requirements")

            # Save after each successful generation (safe to interrupt)
            doc["last_updated"] = __import__("datetime").date.today().isoformat()
            with open(REGS_FILE, "w", encoding="utf-8") as f:
                json.dump(doc, f, indent=2, ensure_ascii=False)

            if i < len(to_add):
                time.sleep(RATE_DELAY)

        except Exception as e:
            print(f"         ✗ ERROR: {e}")
            errors.append((reg["id"], str(e)))
            # Save progress even after error
            doc["last_updated"] = __import__("datetime").date.today().isoformat()
            with open(REGS_FILE, "w", encoding="utf-8") as f:
                json.dump(doc, f, indent=2, ensure_ascii=False)

    print(f"\n{'='*50}")
    print(f"Done. Added {added}/{len(to_add)} regulations.")
    if errors:
        print(f"\nFailed ({len(errors)}):")
        for reg_id, err in errors:
            print(f"  {reg_id}: {err}")
    print(f"\nNext steps:")
    print(f"  1. python scripts/enrich_requirements.py   (add how_to_meet / vendor_actions to any missing)")
    print(f"  2. python scripts/check_regulation_updates.py  (rebuild hashes)")
    print(f"  3. git add data/regulations.json && git commit && git push")


if __name__ == "__main__":
    main()
